### ISSUE TITLE
Оформление

### ISSUE THREAD

**Issue by YegorMan** [DashaPrincess/my-works#2]
https://github.com/DashaPrincess/my-works/blob/1bb6a03e691723dda8b2872fbb716df22c6a1485/practice%20tl/calc/calculatorLib/iCalculator.cs#L3

Namespaces, интерфейсы и имена файлов должны начитаться с заглавной буквы

**Comment by YegorMan** [comment]
Это касается не только этого места, посмотри, пожалуйста, во всем проекте

**Comment by DashaPrincess** [comment]
все, что лежит в этой папке  - моя первая попытка сделать на практике в кабинете приложение калькулятор, и с ним были какие-то проблемы. нормальное рабочее приложение лежало в папке LW2(сейчас уже переименовала в app-calc), а дома в качестве первой домашней работы я делала просто программу, я поместила ее в папку me-program-calc
